### 感知机代码

 - Perception 的原始形式
 - Perception 的对偶形式

In [1]:
#原始的数学形式
import numpy as np
import matplotlib.pyplot as plt
import imageio
import os

In [36]:
class PerceptionMethod(object):  # 定义感知机学习类
    def __init__(self, X, Y, eta):  # 类中参数是 X,Y（X,Y)均为numpy数组,eta是学习率
        if X.shape[0] != Y.shape[0]:  # 要求X,Y中的数目一样，即一个x对应一个y,否则返回错误
            raise ValueError('Error,X and Y must be same when axis=0 ')
        else:  # 在类中储存参数
            self.X = X
            self.Y = Y
            self.eta = eta
    def ini_Per(self):  # 感知机的原始形式
        weight = np.zeros(self.X.shape[1])  # 初始化weight,b
        b = 0
        number = 0  # 记录训练次数
        mistake = True  # mistake是变量用来说明分类是否有错误
        while mistake is True:  # 当有错时
            mistake = False  # 开始下一轮纠错前需要将mistake变为true，一来判断这一轮是否有错误
            for index in range(self.X.shape[0]):  # 循环开始
                if self.Y[index] * (weight @ self.X[index] + b) <= 0:  # 错误判断条件
                    weight += self.eta * self.Y[index] * self.X[index]  # 进行更新weight，b
                    b += self.eta * self.Y[index]
                    number += 1
                    print(weight, b,number)
                    mistake = True  # 此轮检查出错误，表明mistake为true，进行下列一轮
                    break  # 找出第一个错误后调出循环
        return weight, b  # 返回值
   
    def dual_Per(self): #对偶形式
            Gram = np.dot(self.X, self.X.T)
            alpha = np.zeros(self.X.shape[0])
            b = 0
            mistake = True
            while mistake is True:
                mistake = False
                for index in range(self.X.shape[0]):
                    if self.Y[index] * (alpha * self.Y @ Gram[index] + b) <= 0:
                        alpha[index] += self.eta
                        b += self.eta * self.Y[index]
                        print(alpha, b)
                        mistake = True
                        break
            weight = self.Y * alpha @ self.X
            return weight, b

In [37]:
# 一个例子
X = np.array([[3, 3], [4, 3], [1, 1]])
Y = np.array([1, 1, -1])
PER = PerceptionMethod(X, Y, 1)
print(PER.ini_Per())
print(PER.dual_Per())

[3. 3.] 1 1
[2. 2.] 0 2
[1. 1.] -1 3
[0. 0.] -2 4
[3. 3.] -1 5
[2. 2.] -2 6
[1. 1.] -3 7
(array([1., 1.]), -3)
[1. 0. 0.] 1
[1. 0. 1.] 0
[1. 0. 2.] -1
[1. 0. 3.] -2
[2. 0. 3.] -1
[2. 0. 4.] -2
[2. 0. 5.] -3
(array([1., 1.]), -3)
